### PR TITLE
Compatibility with Moodle 4.5 done differently.

### PR DESCRIPTION
**Pull request by lucaboesch**
In order not to clash with other filter plugins, the way to go should be the one in this branch.
Also, Moodle Plugin CI id updated to more modern PHP/Moodle versions.

### CODE REVIEW

**Comment by FMCorz** [comment]
Hi @lucaboesch,

Thanks for sending this PR. Can you please elaborate on the clash with other plugins and your preference of a class_alias over dynamical classes? I'm not sure I see the benefit at first glance.

One of the reason I prefer the latter is that some IDEs, such as VS Code, do not resolve aliases.

**Comment by lucaboesch** [comment]
Hi @FMCorz 
I think as soon as there would be a second filter using the same
`class text_filter extends core_text_filter`
there would be a clash, wouldn't it?

**Comment by FMCorz** [comment]
@lucaboesch I believe the class is namespaced so there shouldn't be.

**Comment by lucaboesch** [comment]
Well, you are probably right, and finally it is up to you.
What I did is to make automated Plugin CI tests passing for filter_shortcodes.
It seems though that although for IDEs it is better to code it the other way round you would hit a 
```
Duplicate class name "filter_shortcodes\core_text_filter" found; first defined in
    |         | /home/runner/work/moodle-filter_shortcodes/moodle-filter_shortcodes/moodle/filter/shortcodes/classes/text_filter.php
    |         | on line 39 (Generic.Classes.DuplicateClassName.Found)
```
warning.
I had to circumvent it by adding
`// phpcs:disable Generic.Classes.DuplicateClassName.Found.`

https://github.com/branchup/moodle-filter_shortcodes/pull/9

**Pull request closed without merging**
